### ISSUE TITLE
When put new plugin to repository "Packagist"?

### ISSUE THREAD

**Issue by kukrik** [qcubed/plugin_signaturepad#2]
@olegabr, if you already have a new plugin  in repository "Packagist"? Anyway there https://packagist.org/packages/qcubed/ not your plugin inside list...

When did you put it there?

**Comment by olegabr** [comment]
I don't know how to do that. it needs some credentials. @spekary, may be you know these credentials?

**Comment by spekary** [comment]
You have to create your own account.

**Comment by olegabr** [comment]
I did it, but I can not post projects to the qcubed namespace. It is bound to the address it was first registered to.

**Comment by kukrik** [comment]
@spekary, I just thought it @olegabr last comment is important. This the namespace I thought... This is one thing.

Another thing - how for test the new plugin to use a different namespace? For me the confusing theory.

@spekary, can you put in place clear rules of the game? 

EDIT: I also have there own account, but I do not have yet a new plugin. @olegabr is now the first man. I want to see how this thing will succeed.

**Comment by kukrik** [comment]
How is it going?

**Comment by spekary** [comment]
I didn’t know these accounts owned a github project like that.

I have changed my Packagist account to the following credentials, so that we can share it with the lead developers:

qcubed
QcubedBeta3

That way you can see how to add this to packagist and help others too.

Shannon

> On Jul 23, 2016, at 11:11 AM, Oleg Abrosimov notifications@github.com wrote:
> 
> I did it, but I can not post projects to the qcubed namespace. It is bound to the address it was first registered to.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Shannon Pekary
spekary@gmail.com

**Comment by olegabr** [comment]
with this credentials I was able to login to https://packagist.org/ and add the plugin there: https://packagist.org/packages/qcubed/plugin_signaturepad

**Comment by olegabr** [comment]
And I've added an autoupdate hook too.
